<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260122075420 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE notification DROP CONSTRAINT fk_bf5476ca67b3b43d');
        $this->addSql('DROP TABLE notification');
        $this->addSql('ALTER TABLE project ALTER project_desc TYPE TEXT');
        $this->addSql('ALTER TABLE project ALTER project_created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE tasks ALTER task_due_date DROP NOT NULL');
        $this->addSql('ALTER TABLE tasks ALTER task_project_id SET NOT NULL');
        $this->addSql('DROP INDEX uniq_identifier_email');
        $this->addSql('ALTER TABLE "user" ALTER roles TYPE JSON');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE notification (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(255) NOT NULL, message TEXT NOT NULL, link VARCHAR(255) NOT NULL, is_read BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, users_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_bf5476ca67b3b43d ON notification (users_id)');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT fk_bf5476ca67b3b43d FOREIGN KEY (users_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE project ALTER project_desc TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE project ALTER project_created_at TYPE DATE');
        $this->addSql('ALTER TABLE tasks ALTER task_due_date SET NOT NULL');
        $this->addSql('ALTER TABLE tasks ALTER task_project_id DROP NOT NULL');
        $this->addSql('ALTER TABLE "user" ALTER roles TYPE JSONB');
        $this->addSql('CREATE UNIQUE INDEX uniq_identifier_email ON "user" (email)');
    }
}
