<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260115091930 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE notification (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, message VARCHAR(255) NOT NULL, is_read BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_BF5476CAA76ED395 ON notification (user_id)');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CAA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE th ADD task_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE th ADD author_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE th ALTER th_updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE th ADD CONSTRAINT FK_49E347678DB60186 FOREIGN KEY (task_id) REFERENCES tasks (id)');
        $this->addSql('ALTER TABLE th ADD CONSTRAINT FK_49E34767F675F31B FOREIGN KEY (author_id) REFERENCES "user" (id)');
        $this->addSql('CREATE INDEX IDX_49E347678DB60186 ON th (task_id)');
        $this->addSql('CREATE INDEX IDX_49E34767F675F31B ON th (author_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE notification DROP CONSTRAINT FK_BF5476CAA76ED395');
        $this->addSql('DROP TABLE notification');
        $this->addSql('ALTER TABLE th DROP CONSTRAINT FK_49E347678DB60186');
        $this->addSql('ALTER TABLE th DROP CONSTRAINT FK_49E34767F675F31B');
        $this->addSql('DROP INDEX IDX_49E347678DB60186');
        $this->addSql('DROP INDEX IDX_49E34767F675F31B');
        $this->addSql('ALTER TABLE th DROP task_id');
        $this->addSql('ALTER TABLE th DROP author_id');
        $this->addSql('ALTER TABLE th ALTER th_updated_at TYPE DATE');
    }
}
