<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260122080808 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE notification (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(255) NOT NULL, message TEXT NOT NULL, link VARCHAR(255) NOT NULL, is_read BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, users_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_BF5476CA67B3B43D ON notification (users_id)');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CA67B3B43D FOREIGN KEY (users_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE project ALTER project_desc TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE project ALTER project_created_at TYPE DATE');
        $this->addSql('ALTER TABLE tasks ALTER task_due_date SET NOT NULL');
        $this->addSql('ALTER TABLE tasks ALTER task_project_id DROP NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE notification DROP CONSTRAINT FK_BF5476CA67B3B43D');
        $this->addSql('DROP TABLE notification');
        $this->addSql('ALTER TABLE project ALTER project_desc TYPE TEXT');
        $this->addSql('ALTER TABLE project ALTER project_created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE tasks ALTER task_due_date DROP NOT NULL');
        $this->addSql('ALTER TABLE tasks ALTER task_project_id SET NOT NULL');
        $this->addSql('DROP INDEX UNIQ_IDENTIFIER_EMAIL');
    }
}
