<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251126154412 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE priority (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, priority_name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE project (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, project_name VARCHAR(255) NOT NULL, project_desc VARCHAR(255) NOT NULL, project_created_at DATE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE role (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, role_name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE status (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status_name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE tasks (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, task_title VARCHAR(255) NOT NULL, task_desc VARCHAR(255) NOT NULL, task_due_date DATE NOT NULL, task_created_at DATE NOT NULL, task_last_change DATE NOT NULL, task_priority_id INT DEFAULT NULL, task_status_id INT DEFAULT NULL, task_project_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_50586597F0EB4CB ON tasks (task_priority_id)');
        $this->addSql('CREATE INDEX IDX_5058659714DDCDEC ON tasks (task_status_id)');
        $this->addSql('CREATE INDEX IDX_50586597A7E5433 ON tasks (task_project_id)');
        $this->addSql('CREATE TABLE th (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, th_changelog VARCHAR(255) NOT NULL, th_updated_at DATE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0 ON messenger_messages (queue_name)');
        $this->addSql('CREATE INDEX IDX_75EA56E0E3BD61CE ON messenger_messages (available_at)');
        $this->addSql('CREATE INDEX IDX_75EA56E016BA31DB ON messenger_messages (delivered_at)');
        $this->addSql('ALTER TABLE tasks ADD CONSTRAINT FK_50586597F0EB4CB FOREIGN KEY (task_priority_id) REFERENCES priority (id)');
        $this->addSql('ALTER TABLE tasks ADD CONSTRAINT FK_5058659714DDCDEC FOREIGN KEY (task_status_id) REFERENCES status (id)');
        $this->addSql('ALTER TABLE tasks ADD CONSTRAINT FK_50586597A7E5433 FOREIGN KEY (task_project_id) REFERENCES project (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE tasks DROP CONSTRAINT FK_50586597F0EB4CB');
        $this->addSql('ALTER TABLE tasks DROP CONSTRAINT FK_5058659714DDCDEC');
        $this->addSql('ALTER TABLE tasks DROP CONSTRAINT FK_50586597A7E5433');
        $this->addSql('DROP TABLE priority');
        $this->addSql('DROP TABLE project');
        $this->addSql('DROP TABLE role');
        $this->addSql('DROP TABLE status');
        $this->addSql('DROP TABLE tasks');
        $this->addSql('DROP TABLE th');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
